### ISSUE TITLE
Rotate Kong logs

### ISSUE THREAD

**Issue by altexy** [GluuFederation/gluu-gateway-setup#13]
It would be great if we will provide some log rotate strategy for different deploy types.
For example, for OS package we may install logrotate and some default config for it.

For Docker logs are redirected to standard Docker logs, so any external solution may be applicable.

**Comment by nikdavnik** [comment]
@ldeveloperl1985 added logrotate as dependency for gg package

**Comment by ldeveloperl1985** [comment]
Done
