### ISSUE TITLE
One service start/stop other services

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/gluu-gateway-setup#6]
One service starting or stopping other services. Facing this issue in CentOS and REHL7.

Expected Behaviour:
`konga` service should only start konga UI. `kong` service should only stop/start kong.

Actual Behaviour:
`konga` service starting UI as well as starting `kong` also. `kong` service starting/stopping kong as well as starting/stopping OXD/DB/KongaUI. OXD service is also not working properly(Testing by Centoxy team)

Environment:
CentOS 7
REHL 7
GG 4.0

**Comment by ldeveloperl1985** [comment]
@nikdavnik we are still facing this issue, please fix it.

**Comment by nikdavnik** [comment]
Removed kong and konga depndencies in last packages

**Comment by ldeveloperl1985** [comment]
@nikdavnik @adrian-gluu I've tested. it is working well in Ub16 but the same behavior in the Ub18 case so please check in the Ub18 case. when I hit `systemctl stop konga`, it is stopping konga as well as stopping kong service so please check once

**Comment by ldeveloperl1985** [comment]
@adrian-gluu test your new build and it is working, also the same issue for centos case so please apply a fix for centos case also
